columns_by_table_clean = {'Anthrax': 'a',
 'Arboviral diseases': 'c',
 'Botulism': 'c',
 'Babesiosis': 'c',
 'Chancroid': 'd',
 'Brucellosis': 'd',
 'Cholera': 'd',
 'Campylobacteriosis': 'd',
 'Chlamydia trachomatis infection': 'd',
 'Coccidioidomycosis *': 'd',
 'Cryptosporidiosis': 'd',
 'Cyclosporiasis': 'e',
 'Diphtheria': 'e',
 'Dengue virus infections': 'e',
 'Ehrlichiosis and Anaplasmosis': 'e',
 'Gonorrhea': 'f',
 "Hansen's disease": 'f',
 'Haemophilus influenzae': 'f',
 'Giardiasis': 'f',
 'Hepatitis': 'g',
 'Hemolytic uremic syndrome post-diarrheal': 'g',
 'Hantavirus infection': 'g',
 'Hantavirus pulmonary syndrome': 'g',
 'Influenza-associated pediatric mortality': 'h',
 'Invasive pneumococcal disease': 'h',
 'Leptospirosis': 'h',
 'Human immunodeficiency virus diagnoses': 'h',
 'HIV': 'h',
 'Legionellosis': 'h',
 'Malaria': 'i',
 'Measles': 'i',
 'Lyme disease': 'i',
 'Listeriosis': 'i',
 'Mumps': 'j',
 'Meningococcal disease': 'j',
 'Paratyphoid fever *': 'j',
 'Novel Influenza A virus infections': 'j',
 'Poliomyelitis': 'k',
 'Psittacosis': 'k',
 'Plague': 'k',
 'Pertussis': 'k',
 'Q fever': 'k',
 'Poliovirus infection': 'k',
 'Rabies': 'l',
 'Salmonellosis (excluding paratyphoid fever and typhoid fever) *': 'l',
 'Rubella': 'l',
 'Severe acute respiratory syndrome-associated coronavirus disease': 'l',
 'Smallpox': 'm',
 'Spotted fever rickettsiosis': 'm',
 'Streptococcal toxic shock syndrome': 'm',
 'Shigellosis': 'm',
 'Shiga toxin-producing Escherichia coli (STEC)': 'm',
 'Tetanus': 'n',
 'Syphilis': 'n',
 'Tularemia': 'n',
 'Toxic shock syndrome (other than Streptococcal)': 'n',
 'Trichinellosis': 'n',
 'Tuberculosis': 'n',
 'Vibriosis': 'o',
 'Typhoid fever': 'o',
 'Vancomycin-intermediate Staphylococcus aureus': 'o',
 'Varicella mortality': 'o',
 'Vancomycin-resistant Staphylococcus aureus': 'o',
 'Varicella morbidity': 'o',
 'Viral hemorrhagic fevers': 'p'}
columns_by_table = {
 'a': ['Anthrax',
  'Arboviral diseases, Chikungunya virus disease',
  'Arboviral diseases, Eastern equine encephalitis virus disease, Neuroinvasive',
  'Arboviral diseases, Eastern equine encephalitis virus disease, Non-neuroinvasive',
  'Arboviral diseases, Jamestown Canyon  virus disease, Neuroinvasive',
  'Arboviral diseases, Jamestown Canyon  virus disease, Non-neuroinvasive'],
 'b': ['Arboviral diseases, La Crosse  virus disease, Neuroinvasive',
  'Arboviral diseases, La Crosse  virus disease, Non-neuroinvasive',
  'Arboviral diseases, Powassan virus disease, Neuroinvasive',
  'Arboviral diseases, Powassan virus disease, Non-neuroinvasive',
  'Arboviral diseases, St. Louis encephalitis virus disease, Neuroinvasive',
  'Arboviral diseases, St. Louis encephalitis virus disease, Non-neuroinvasive',
  'Arboviral diseases, West Nile virus disease, Neuroinvasive',
  'Arboviral diseases, West Nile virus disease, Non-neuroinvasive'],
 'c': ['Arboviral diseases, Western equine encephalitis virus disease, Neuroinvasive',
  'Arboviral diseases, Western equine encephalitis virus disease, Non-neuroinvasive',
  'Babesiosis, Total',
  'Babesiosis, Confirmed',
  'Babesiosis, Probable',
  'Botulism, Total',
  'Botulism, Foodborne',
  'Botulism, Infant',
  'Botulism, Other (wound & unspecified)'],
 'd': ['Brucellosis',
  'Campylobacteriosis',
  'Chancroid',
  'Chlamydia trachomatis infection',
  'Cholera',
  'Coccidioidomycosis *',
  'Cryptosporidiosis, Total',
  'Cryptosporidiosis, Confirmed',
  'Cryptosporidiosis, Probable'],
 'e': ['Cyclosporiasis',
  'Dengue virus infections, Dengue *',
  'Dengue virus infections, Dengue-like illness *',
  'Dengue virus infections, Severe dengue *',
  'Diphtheria',
  'Ehrlichiosis and Anaplasmosis, Anaplasma phagocytophilum infection',
  'Ehrlichiosis and Anaplasmosis, Ehrlichia chaffeensis infection',
  'Ehrlichiosis and Anaplasmosis, Ehrlichia ewingii infection',
  'Ehrlichiosis and Anaplasmosis, Undetermined ehrlichiosis/anaplasmosis'],
 'f': ['Giardiasis',
  'Gonorrhea',
  'Haemophilus influenzae, invasive disease, All ages, all serotypes',
  'Haemophilus influenzae, invasive disease, Age <5 years, Serotype b',
  'Haemophilus influenzae, invasive disease, Age <5 years, Nontypeable',
  'Haemophilus influenzae, invasive disease, Age <5 years, Unknown serotype',
  'Haemophilus influenzae, invasive disease, Age <5 years, Non-b serotype',
  "Hansen's disease"],
 'g': ['Hantavirus infection, non-hantavirus pulmonary syndrome',
  'Hantavirus pulmonary syndrome',
  'Hemolytic uremic syndrome post-diarrheal',
  'Hepatitis, A, acute *',
  'Hepatitis, B, acute *',
  'Hepatitis, B, perinatal infection *',
  'Hepatitis, C, acute, Confirmed *',
  'Hepatitis, C, acute, Probable *',
  'Hepatitis, C, perinatal infection *'],
 'h': ['Human immunodeficiency virus diagnoses',
  'Influenza-associated pediatric mortality',
  'Invasive pneumococcal disease, All ages, Confirmed *',
  'Invasive pneumococcal disease, All ages, Probable *',
  'Invasive pneumococcal disease, Age <5 years, Confirmed *',
  'Invasive pneumococcal disease, Age <5 years, Probable *',
  'Legionellosis',
  'Leptospirosis'],
 'i': ['Listeriosis',
  'Lyme disease, Total',
  'Lyme disease, Confirmed',
  'Lyme disease, Probable',
  'Malaria',
  'Measles, Total',
  'Measles, Indigenous',
  'Measles, Imported'],
 'j': ['Meningococcal disease, All serogroups',
  'Meningococcal disease, Serogroups ACWY',
  'Meningococcal disease, Serogroup B',
  'Meningococcal disease, Other serogroups',
  'Meningococcal disease, Unknown serogroup',
  'Mumps',
  'Novel Influenza A virus infections',
  'Paratyphoid fever *'],
 'k': ['Pertussis',
  'Plague',
  'Poliomyelitis, paralytic',
  'Poliovirus infection, nonparalytic',
  'Psittacosis',
  'Q fever, Total',
  'Q fever, Acute',
  'Q fever, Chronic'],
 'l': ['Rabies, Animal',
  'Rabies, Human',
  'Rubella',
  'Rubella, congenital syndrome',
  'Salmonellosis (excluding paratyphoid fever and typhoid fever) *',
  'Severe acute respiratory syndrome-associated coronavirus disease'],
 'm': ['Shiga toxin-producing Escherichia coli (STEC)',
  'Shigellosis',
  'Smallpox',
  'Spotted fever rickettsiosis, Total',
  'Spotted fever rickettsiosis, Confirmed',
  'Spotted fever rickettsiosis, Probable',
  'Streptococcal toxic shock syndrome'],
 'n': ['Syphilis, Total, all stages *',
  'Syphilis, Congenital',
  'Syphilis, Primary and secondary',
  'Tetanus',
  'Toxic shock syndrome (other than Streptococcal)',
  'Trichinellosis',
  'Tuberculosis',
  'Tularemia'],
 'o': ['Typhoid fever',
  'Vancomycin-intermediate Staphylococcus aureus',
  'Vancomycin-resistant Staphylococcus aureus',
  'Varicella morbidity',
  'Varicella mortality',
  'Vibriosis, Total',
  'Vibriosis, Confirmed',
  'Vibriosis, Probable'],
 'p': ['Viral hemorrhagic fevers, Crimean-Congo hemorrhagic fever virus',
  'Viral hemorrhagic fevers, Ebola virus',
  'Viral hemorrhagic fevers, Guanarito virus',
  'Viral hemorrhagic fevers, Junin virus',
  'Viral hemorrhagic fevers, Lassa virus',
  'Viral hemorrhagic fevers, Lujo virus',
  'Viral hemorrhagic fevers, Machupo virus',
  'Viral hemorrhagic fevers, Marburg virus',
  'Viral hemorrhagic fevers, Sabia virus']
}